version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/localhost.pem:/etc/nginx/localhost.pem
            - ./nginx/localhost-key.pem:/etc/nginx/localhost-key.pem
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: ${APP_NAME}-mysql
        tty: true
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build: .
        container_name: ${APP_NAME}-php
        user: "1000"
        volumes:
            - .:/var/www/html
            - ./custom-php.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_DB_SERVER: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
            restart: always
        ports:
            - "8081:80"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata: {}
