version: '3'

services:
    app:
        build: .
        user: "1000"
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
            - .user.ini:/usr/local/etc/php/conf.d/user.ini
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - laravel

    redis:
        image: redis:4.0
        ports:
          - "6379:6379"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - .user.ini:/usr/local/etc/php/conf.d/user.ini
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
