version: '3'

services:
    php:
        build: .
        user: "1000"
        volumes:
            - .:/var/www/html
            - ./custom-php.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/localhost.pem:/etc/nginx/localhost.pem
            - ./nginx/localhost-key.pem:/etc/nginx/localhost-key.pem
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
