version: '3'

services:
    app:
        build: .
        user: "1000"
        volumes:
            - .:/var/www/html
            - .user.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
